export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  DASHBOARD: '/dashboard',
  PROJECTS: '/projects',
  PROJECT_NEW: '/projects/new',
  PROJECT_DETAIL: (id: string | number) => `/projects/${id}`,
  PROJECT_EDIT: (id: string | number) => `/projects/${id}/edit`,
  WORKERS: '/workers',
  WORKER_DETAIL: (id: string | number) => `/workers/${id}`,
  WORKER_PROFILE: '/workers/profile',
  ATTENDANCE: '/workers/attendance',
  SUBCONTRACTORS: '/subcontractors',
  SUBCONTRACTOR_DETAIL: (id: string | number) => `/subcontractors/${id}`,
  CLIENT_POSTINGS: '/clients/postings',
  CLIENT_MATCHING: '/clients/matching',
  CLIENT_TEAM: '/clients/team',
  EXPENSES: '/expenses',
  EXPENSE_NEW: '/expenses/new',
  EXPENSE_DETAIL: (id: string | number) => `/expenses/${id}`,
  DOCUMENTS: '/documents',
  DOCUMENT_UPLOAD: '/documents/upload',
  NOTIFICATIONS: '/notifications',
  REPORTS: '/reports',
  REPORT_DETAIL: (type: string) => `/reports/${type}`,
  SETTINGS: '/settings',
  ADMIN: '/admin',
  ADMIN_USERS: '/admin/users',
  PRICING: '/pricing',
  BILLING: '/billing',
} as const;
