export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  VERIFY: '/verify',
  DASHBOARD: '/dashboard',
  ALERTS: '/alerts',
  WORKERS: '/workers',
  WORKER_DETAIL: (id: string | number) => `/workers/${id}`,
  PROJECTS: '/projects',
  PROJECT_NEW: '/projects/new',
  PROJECT_DETAIL: (id: string | number) => `/projects/${id}`,
  PROJECT_EDIT: (id: string | number) => `/projects/${id}/edit`,
  EXPENSES: '/expenses',
  EXPENSE_NEW: '/expenses/new',
  EXPENSE_DETAIL: (id: string | number) => `/expenses/${id}`,
  PIPELINE: '/pipeline',
  PIPELINE_DETAIL: (id: string | number) => `/pipeline/${id}`,
  NOTIFICATIONS: '/notifications',
  SETTINGS: '/settings',
} as const;
